package com.sales.app.presentation.payments

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.sales.app.domain.model.Party
import com.sales.app.domain.model.Transaction
import com.sales.app.domain.repository.PartyRepository
import com.sales.app.domain.repository.PaymentRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import com.sales.app.util.TimeProvider
import kotlinx.datetime.TimeZone
import kotlinx.datetime.toLocalDateTime

@OptIn(kotlin.time.ExperimentalTime::class)
class PaymentFormViewModel(
    private val paymentRepository: PaymentRepository,
    private val partyRepository: PartyRepository
) : ViewModel() {

    private val _parties = MutableStateFlow<List<Party>>(emptyList())
    val parties: StateFlow<List<Party>> = _parties.asStateFlow()

    private val _isLoading = MutableStateFlow(false)
    val isLoading: StateFlow<Boolean> = _isLoading.asStateFlow()

    private val _error = MutableStateFlow<String?>(null)
    val error: StateFlow<String?> = _error.asStateFlow()

    fun loadParties(companyId: Int) {
        viewModelScope.launch {
            partyRepository.getPartiesByAccount(companyId).collect {
                _parties.value = it
            }
        }
    }

    fun createPayment(
        companyId: Int,
        partyId: Int,
        amount: Double,
        isReceived: Boolean,
        comment: String?,
        onSuccess: () -> Unit
    ) {
        viewModelScope.launch {
            _isLoading.value = true
            val today = TimeProvider.now().toLocalDateTime(TimeZone.currentSystemDefault()).date.toString()
            
            // Determine codes based on type
            // Received: Debit Party, Credit Cash (0)
            // Paid: Debit Cash (0), Credit Party
            val debitCode = if (isReceived) partyId else 0
            val creditCode = if (!isReceived) partyId else 0
            
            // Type: 1=Cash Received, 2=Cash Paid (Simplification)
            val type = if (isReceived) 1 else 2

            val transaction = Transaction(
                id = 0, // Generated by backend
                date = today,
                amount = amount,
                type = type,
                debitCode = debitCode,
                creditCode = creditCode,
                comment = comment,
                isReceived = isReceived
            )

            val result = paymentRepository.createTransaction(transaction)
            result.onSuccess {
                onSuccess()
            }.onFailure {
                _error.value = it.message
            }
            _isLoading.value = false
        }
    }
}
